import { describe, expect, it } from 'vitest';
import { entry, runReport } from './helpers/gh-stub';

const AKIRA_MARK = entry('components', 'akira-mark', '@akira-io/ui');
const LOGIN_FORM = entry('blocks', 'login-form', '@akira-io/ui/blocks');

const ONE = JSON.stringify([AKIRA_MARK]);
const TWO = JSON.stringify([AKIRA_MARK, LOGIN_FORM]);
const TWO_REVERSED = JSON.stringify([LOGIN_FORM, AKIRA_MARK]);

function bodyWith(list: string, notes = '') {
    return [
        'These akira-io/ui exports have no folder under src/demos.',
        notes,
        '<!-- missing-examples:start -->',
        '- `components/akira-mark` from `@akira-io/ui`',
        '',
        '```json',
        list,
        '```',
        'Run: https://example.test/run/0',
        '<!-- missing-examples:end -->',
        '',
        'Generated by flag-missing-examples.yml in akira-io/ui.',
    ].join('\n');
}

function commandsOf(calls: { command: string }[]) {
    return calls.map((call) => call.command);
}

function bodyOf(call: { args: string[] }) {
    return call.args[call.args.indexOf('--body') + 1];
}

describe('report-missing-examples.sh', () => {
    it('refuses a detector output that is not a JSON array', () => {
        const run = runReport({ missing: '' });

        expect(run.status).toBe(1);
        expect(run.stderr).toContain('the detector produced no JSON array');
        expect(run.calls).toEqual([]);
    });

    it('does nothing when nothing is missing and no issue is open', () => {
        const run = runReport({ missing: '[]' });

        expect(run.status).toBe(0);
        expect(commandsOf(run.calls)).toEqual(['issue list']);
    });

    it('comments and closes the open issue once nothing is missing', () => {
        const run = runReport({ missing: '[]', openIssue: '7' });

        expect(run.status).toBe(0);
        expect(commandsOf(run.calls)).toEqual([
            'issue list',
            'issue comment',
            'issue close',
        ]);
    });

    it('opens one issue listing every entry when none is open', () => {
        const run = runReport({ missing: TWO });

        expect(commandsOf(run.calls)).toEqual(['issue list', 'issue create']);

        const body = bodyOf(run.calls[1]);

        expect(body).toContain(
            '- `blocks/login-form` from `@akira-io/ui/blocks`',
        );
        expect(body).toContain('- `components/akira-mark` from `@akira-io/ui`');
        expect(body).toContain('<!-- missing-examples:start -->');
        expect(body).toContain('<!-- missing-examples:end -->');
    });

    it('stays silent when the recorded list matches', () => {
        const run = runReport({
            missing: ONE,
            openIssue: '7',
            issueBody: bodyWith(ONE),
        });

        expect(commandsOf(run.calls)).toEqual(['issue list', 'issue view']);
        expect(run.stdout).toContain('the list has not changed');
    });

    it('stays silent when only the order of the entries differs', () => {
        const run = runReport({
            missing: TWO_REVERSED,
            openIssue: '7',
            issueBody: bodyWith(TWO),
        });

        expect(commandsOf(run.calls)).toEqual(['issue list', 'issue view']);
    });

    it('edits and comments when the list actually changed', () => {
        const run = runReport({
            missing: TWO,
            openIssue: '7',
            issueBody: bodyWith(ONE),
        });

        expect(commandsOf(run.calls)).toEqual([
            'issue list',
            'issue view',
            'issue view',
            'issue edit',
            'issue comment',
        ]);
        expect(bodyOf(run.calls[4])).toContain('The list changed:');
    });

    it('keeps what a person wrote outside the generated block', () => {
        const run = runReport({
            missing: TWO,
            openIssue: '7',
            issueBody: bodyWith(ONE, 'Taking akira-mark this week. -- kid'),
        });

        const body = bodyOf(run.calls[3]);

        expect(body).toContain('Taking akira-mark this week. -- kid');
        expect(body).toContain('Generated by flag-missing-examples.yml');
        expect(body).toContain('- `blocks/login-form`');
        expect(body).not.toContain(`\n${ONE}\n`);
    });

    it('collapses a body that carries the marker block twice', () => {
        const run = runReport({
            missing: TWO,
            openIssue: '7',
            issueBody: `${bodyWith(ONE)}\n${bodyWith(ONE)}`,
        });

        const body = bodyOf(run.calls[3]);
        const starts = body.match(/<!-- missing-examples:start -->/g) ?? [];

        expect(starts).toHaveLength(1);
    });

    it('rebuilds a body whose closing marker was deleted', () => {
        const run = runReport({
            missing: TWO,
            openIssue: '7',
            issueBody: bodyWith(ONE).replace(
                '<!-- missing-examples:end -->',
                '',
            ),
        });

        const body = bodyOf(run.calls[3]);

        expect(body).toContain('<!-- missing-examples:start -->');
        expect(body).toContain('<!-- missing-examples:end -->');
        expect(body).toContain('- `blocks/login-form`');
    });

    it('opens no issue when one is already open', () => {
        const run = runReport({
            missing: TWO,
            openIssue: '7',
            issueBody: bodyWith(ONE),
        });

        expect(commandsOf(run.calls)).not.toContain('issue create');
    });

    it('never reaches for the search index to find the issue', () => {
        const run = runReport({ missing: '[]' });

        expect(run.calls[0].args).toContain('--limit');
        expect(run.calls[0].args.join(' ')).not.toContain('--search');
    });
});
