#!/usr/bin/env bash
set -euo pipefail

: "${SITE_REPO:?SITE_REPO is required}"
: "${ISSUE_TITLE:?ISSUE_TITLE is required}"
: "${MISSING?MISSING is required}"
RUN_URL="${RUN_URL:-}"

MARKER_START='<!-- missing-examples:start -->'
MARKER_END='<!-- missing-examples:end -->'

normalize() {
    jq -Sc 'sort_by(.group, .slug)'
}

find_open_issue() {
    gh issue list --repo "$SITE_REPO" --state open --limit 100 \
        --json number,title \
        --jq '[.[] | select(.title == env.ISSUE_TITLE)][0].number // empty'
}

recorded_entries() {
    gh issue view "$1" --repo "$SITE_REPO" --json body --jq .body |
        tr -d '\r' |
        awk -v start="$MARKER_START" -v end="$MARKER_END" '
            $0 == start { inside = 1; next }
            $0 == end { exit }
            inside && /^\[/ { print; exit }
        '
}

render_block() {
    printf '%s\n' \
        "$MARKER_START" \
        "$LIST" \
        '' \
        '```json' \
        "$ENTRIES" \
        '```' \
        "Run: $RUN_URL" \
        "$MARKER_END"
}

render_body() {
    printf '%s\n' \
        "These akira-io/ui exports have no folder under src/demos, so the site renders no page for them." \
        '' \
        "Entries listed in tests/uncovered-entries.json are deliberately without a demo and never show up here." \
        '' \
        "$BLOCK" \
        '' \
        "Generated by flag-missing-examples.yml in akira-io/ui. Anything written outside the block above survives an update."
}

replace_block() {
    BLOCK="$BLOCK" awk -v start="$MARKER_START" -v end="$MARKER_END" '
        BEGIN { block = ENVIRON["BLOCK"] }
        $0 == start && !seen { print block; seen = 1; dropping = 1; next }
        $0 == start { dropping = 1; next }
        dropping && $0 == end { dropping = 0; next }
        dropping { next }
        { print }
    '
}

case "$MISSING" in
'['*']') ;;
*)
    echo "the detector produced no JSON array: $MISSING" >&2
    exit 1
    ;;
esac

ENTRIES="$(printf '%s' "$MISSING" | normalize)"
NUMBER="$(find_open_issue)"

if [ "$ENTRIES" = '[]' ]; then
    if [ -z "$NUMBER" ]; then
        echo "nothing is missing and no issue is open"
        exit 0
    fi

    gh issue comment "$NUMBER" --repo "$SITE_REPO" \
        --body "Every export now has a demo folder or sits in tests/uncovered-entries.json. Run: $RUN_URL"
    gh issue close "$NUMBER" --repo "$SITE_REPO"
    exit 0
fi

LIST="$(printf '%s' "$ENTRIES" |
    jq -r '.[] | "- `\(.group)/\(.slug)` from `\(.specifier)`"')"
BLOCK="$(render_block)"

if [ -z "$NUMBER" ]; then
    gh issue create --repo "$SITE_REPO" \
        --title "$ISSUE_TITLE" \
        --label documentation \
        --assignee kidiatoliny \
        --body "$(render_body)"
    exit 0
fi

RECORDED="$(recorded_entries "$NUMBER")"

if [ -n "$RECORDED" ] && printf '%s' "$RECORDED" | jq -e . >/dev/null 2>&1; then
    if [ "$(printf '%s' "$RECORDED" | normalize)" = "$ENTRIES" ]; then
        echo "the list has not changed since the issue was last updated"
        exit 0
    fi
fi

BODY="$(gh issue view "$NUMBER" --repo "$SITE_REPO" --json body --jq .body | tr -d '\r')"

case "$BODY" in
*"$MARKER_START"*"$MARKER_END"*)
    UPDATED="$(printf '%s\n' "$BODY" | replace_block)"
    ;;
*)
    UPDATED="$(render_body)"
    ;;
esac

gh issue edit "$NUMBER" --repo "$SITE_REPO" --body "$UPDATED"
gh issue comment "$NUMBER" --repo "$SITE_REPO" \
    --body "$(printf '%s\n' "The list changed:" '' "$LIST" '' "Run: $RUN_URL")"
